// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsswQ4EQpNnLy1lXsV3oF3sKabjTXxjj8',
    appId: '1:371111848824:web:c883c96ba4e0d37218f68d',
    messagingSenderId: '371111848824',
    projectId: 'uas-mcc',
    authDomain: 'uas-mcc.firebaseapp.com',
    databaseURL: 'https://uas-mcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-mcc.firebasestorage.app',
    measurementId: 'G-6DRE8DGDD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZeKuZ6NozpJofLFtNu9DJ9N1dEDRx8g',
    appId: '1:371111848824:android:732555eaef1c883118f68d',
    messagingSenderId: '371111848824',
    projectId: 'uas-mcc',
    databaseURL: 'https://uas-mcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-mcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByeGU0A1vTSfKWjXo_AwWUAOeu9uCA7C4',
    appId: '1:371111848824:ios:9e70ec18cd64d9fa18f68d',
    messagingSenderId: '371111848824',
    projectId: 'uas-mcc',
    databaseURL: 'https://uas-mcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-mcc.firebasestorage.app',
    iosClientId: '371111848824-566e72abpo3mqq4r8nlnjsc35q0n7upg.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByeGU0A1vTSfKWjXo_AwWUAOeu9uCA7C4',
    appId: '1:371111848824:ios:9e70ec18cd64d9fa18f68d',
    messagingSenderId: '371111848824',
    projectId: 'uas-mcc',
    databaseURL: 'https://uas-mcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-mcc.firebasestorage.app',
    iosClientId: '371111848824-566e72abpo3mqq4r8nlnjsc35q0n7upg.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMcc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsswQ4EQpNnLy1lXsV3oF3sKabjTXxjj8',
    appId: '1:371111848824:web:6a92783aa9fa6b4518f68d',
    messagingSenderId: '371111848824',
    projectId: 'uas-mcc',
    authDomain: 'uas-mcc.firebaseapp.com',
    databaseURL: 'https://uas-mcc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uas-mcc.firebasestorage.app',
    measurementId: 'G-T3EW9HQTL1',
  );

}